### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by licheng-han** [qingstor/qingstor-sdk-js#102]
vue3+vite 引入sdk 后报 process is not defined
![image](https://user-images.githubusercontent.com/30589386/189796455-c947e38a-97a1-454d-9ea2-b9ea51a50b3b.png)

**Comment by licheng-han** [comment]
![image](https://user-images.githubusercontent.com/30589386/189802049-d384a1c7-1bfe-40a7-8fc4-b551d844241b.png)

**Comment by hosea-hch** [comment]
#92 同样的问题，非sdk本身的bug，属于是使用FAQ @aprilyang

**Comment by licheng-han** [comment]
@hosea-hch 如何解决，目前在vite+vue3框架下初始化sdk便报错

**Comment by aprilyang** [comment]
@hosea-hch 尝试配置一下环境变量？可以参考 https://vitejs.dev/guide/env-and-mode.html#env-files

**Comment by aprilyang** [comment]
@licheng-han 尝试配置一下环境变量？可以参考 https://vitejs.dev/guide/env-and-mode.html#env-files

**Comment by licheng-han** [comment]
@aprilyang 我这边未使用环境变量这种方式，是通过vite define 注入的方式；另外，您的引入方式是process引用，vite已经不在使用这种引入方式，您那边能否加个逻辑判断使用个默认值

**Comment by licheng-han** [comment]
@aprilyang 我这边未使用环境变量这种方式，是通过vite define 注入的方式；另外，您的引入方式是process引用，vite已经不在使用这种引入方式，您那边能否加个逻辑判断使用个默认值

**Comment by aprilyang** [comment]
`import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  define: { process },
})`

in vite.config.js

**Comment by aprilyang** [comment]
`define: { process }` in vite.config.js

**Comment by aprilyang** [comment]
感谢反馈，稍后我们会加上环境变量相关的检测。

**Comment by licheng-han** [comment]
麻烦您，尽快处理下，我这边比较着急上线

**Comment by aprilyang** [comment]
fixed in #103

**Comment by aprilyang** [comment]
@licheng-han version3.1.4 published.
