### ISSUE TITLE
throw error "Request body larger than maxBodyLength limit" when put object larger then 10MB

### ISSUE THREAD

**Issue by markduan** [qingstor/qingstor-sdk-js#67]

**Comment by faller** [comment]
I came across the same problem

**Comment by faller** [comment]
fix this shit with this code

```javascript

const config = new Config({
  access_key_id: 'ACCESS_KEY_ID_EXAMPLE',
  secret_access_key: 'SECRET_ACCESS_KEY_EXAMPLE',
  getAxiosConfig: () => ({ maxContentLength: Infinity, maxBodyLength: Infinity })
});

```

**Comment by markduan** [comment]
great, could you please create a PR to set the axios default?

**Comment by aprilyang** [comment]
fixed in #99 , thanks for your issue.

**Comment by faller** [comment]
<img width="722" alt="截屏2022-08-05 17 13 33" src="https://user-images.githubusercontent.com/3031252/183044999-780de1bc-7710-4a48-b238-49077972f398.png">

**Comment by faller** [comment]
我都服了你了 package main 入口错了
