### ISSUE TITLE
已在服务端获取签名并设置，send 时会再次要求签名

### ISSUE THREAD

**Issue by xiusl** [qingstor/qingstor-sdk-js#71]
调用了 applySignature 方法，req.send 方法内部还会去 sign
![Image](https://likebit.pek3b.qingstor.com/WX20201201-102336%402x.png)
![Image](https://likebit.pek3b.qingstor.com/WX20201201-102504%402x.png)

**Comment by markduan** [comment]
你好，`putObjectRequest` 其实是一个遗留的内部方法，在后面的重构计划中，xxxRequest 等方法都要被去掉。

我看上看的截图，你应该是用到了服务端签名，SDK 支持配置请求服务端签名的 URL，相关文档请参考 [这里](https://github.com/qingstor/qingstor-sdk-js/blob/master/docs/README_zh-cn.md#%E8%AF%B7%E6%B1%82%E7%AD%BE%E5%90%8D).

如果有不清楚的地方请继续在这里直接回复。

**Comment by xiusl** [comment]
我是根据青云文档中提供的这个 [demo](https://github.com/qingstor-incubating/qingstor-sdk-js-demo) 来试的，然而这个 [demo](https://github.com/qingstor-incubating/qingstor-sdk-js-demo)  根本走不通，可能是这边重构了，那边没有同步，最好更新一下。
目前自己用 `axios` 直接上传了。
