### ISSUE TITLE
Cannot read properties of undefined (reading 'MINIPROGRAM')

### ISSUE THREAD

**Issue by shijianzhong** [qingstor/qingstor-sdk-js#92]
vue-router.esm-bundler.js:3295 TypeError: Cannot read properties of undefined (reading 'MINIPROGRAM')
    at qingstor-sdk.js:3092
    at qingstor-sdk.js:3081

**Comment by markduan** [comment]
请问你的 bundle 工具是什么？可以通过配置一下 process.env 暂时解决一下这个问题。

**Comment by shijianzhong** [comment]
> 请问你的 bundle 工具是什么？可以通过配置一下 process.env 暂时解决一下这个问题。

vite

**Comment by markduan** [comment]
我看 vite 支持配置环境变量的，请参考 https://vitejs.dev/guide/env-and-mode.html#env-files

**Comment by aprilyang** [comment]
fixed in #103

**Comment by aprilyang** [comment]
@shijianzhong version3.1.4 published
